### ISSUE TITLE
please clarify some terminology and uses

### ISSUE THREAD

**Issue by rhetr** [mafintosh/hypercore#155]
I would like some clarification on the terms "feed", "stream", and "replication stream":

-It seems like "streams" are specific parts of a "feed" (`createReadStream`, `replicate`) but then I don't understand what a "writable stream" is or how a readable stream is different from a replication stream. 
- What is the difference between "piping" a replication feed to another hypercore and swarming a feed with hyperdiscovery?
- I would also like additional clarification on the general conditions under which feeds/streams are readable and/or writable.

**Comment by pfrazee** [comment]
- **feed**. This is what hypercores are: a data feed. Feeds are permanent data structures that can be shared on the dat network.
 - **stream**. Streams are a tool in the code for reading or writing data. Streams are temporary and almost always returned by functions.
 - **pipe**. Streams tend to either be readable (giving data) or writable (receiving data). If you connect a readable to a writable, that's called piping.
 - **replication stream**. A stream returned by the `replicate()` function which can be piped to a peer. It is used to sync the peers' hypercore feeds.
 - **swarming**. Swarming describes adding yourself to the network, finding peers, and sharing data with them. Piping a replication feed describes sharing the data with one peer.

**Comment by yuriy-yarosh** [comment]
@rhetr I've found that overall hypercore API is inconsistent, so it's understandable that it caused you some frustration.

**Comment by emilbayes** [comment]
@yuriy-yarosh What do you think is inconsistent?

**Comment by mafintosh** [comment]
@pfrazee should we PR that terminology into the README?

**Comment by pfrazee** [comment]
@mafintosh yeah. Ignore @yuriy-yarosh, he's trolling.

**Comment by mafintosh** [comment]
@rhetr see the readme. i've updated it with @pfrazee's comment above. let me know if anything else is confusing and i'll get it fixed. i have a tendency of overusing the same terms for sure!

**Comment by yuriy-yarosh** [comment]
> @yuriy-yarosh What do you think is inconsistent?
@emilbayes 
• poor naming
For instance, [https://github.com/mafintosh/hypercore/blob/master/index.js#L27](Feed constructor), `function Feed (createStorage, key, opts) {` could be `function Feed (storageName, key, opts) {`
and with a static method like `Feed.prototype.with = (builder) => { /* some magic*/}` it's much simpler to distinguish instantiation methods.

This `onwrite` [hook](https://github.com/mafintosh/hypercore/blob/master/index.js#L66), which I suppose was used for testing purposes, but haven't been removed for some reason. There are plenty of mocking libraries for that.

There are way too many options in the Feed constructor itself, some of them are redundant for no reason. For example there's `opts.secretKey` [here](https://github.com/mafintosh/hypercore/blob/master/index.js#L45) and another `opts. storeSecretKey ` [over here](https://github.com/mafintosh/hypercore/blob/master/index.js#L72) some reason, I don't really get the point of these due to poor naming.

`ready` [method](https://github.com/mafintosh/hypercore/blob/master/index.js#L139) should've been named `onReady`

`undownload` [...](https://github.com/mafintosh/hypercore/blob/master/index.js#L326) really  ? Cancelable streams, with a bit of FRP, should've been way more convenient.

• default parameters handling
Well, there's a convention throughout your code like `(parameters, opts, callback)`, but there are plenty of methods that don't need any opts but you're passing 'em anyway and defaulting to `{}` for no particular reason, which causes some confusion. [proof](https://github.com/mafintosh/hypercore/blob/master/index.js#L356) [seek](https://github.com/mafintosh/hypercore/blob/master/index.js#L525) [head](https://github.com/mafintosh/hypercore/blob/master/index.js#L887).

• inconsistant opts handling
There are few methods [get](https://github.com/mafintosh/hypercore/blob/master/index.js#L897) where it's really hard to distinguish between method parameter and an opt, and they've should've been merged, I suppose.

• inconsistant interfaces
For instance, you're accepting a range object `{start: 0, end: 1}` in , but in [downloaded](https://github.com/mafintosh/hypercore/blob/master/index.js#L877) and [has](https://github.com/mafintosh/hypercore/blob/master/index.js#L881) methods you're using method parameters instead.

You might pretend like it's nothing... well, add some [Code Climate](https://codeclimate.com/) and see for yourself.

@emilbayes nowadays, most of OpenSource projects out there, are in fact a pile of crap. I'm not saying that you guys are bad at developing things, it's just bad that you're unable to withstand even a small amount of constructive proposals due to personal cognitive biases and compensational needs. Making even a small amount of critics a personal matter is just showing your unwillingness of improvement. If you've got your personal matter which can't be disclosed - there's always a room for a private, brutally honest talk.

We've got a pile of crap to grow a garden... and you can't do that without accepting some refinement methods. And of course everything is subjective, and I've got my own biases, so, I'm here to discuss, not to argue. 

If you've wanted to establish some conventions - go for some eslint-rules ftw. It's just a yet another proof of [Ikea effect](https://en.wikipedia.org/wiki/IKEA_effect), [broken windows theory](https://en.wikipedia.org/wiki/Broken_windows_theory) and [complaint driven development](https://blog.codinghorror.com/complaint-driven-development/).

You could've replace your `(opts={}, cb)` with some mongo-like `optional callback` convention: if callback is being passed - use it, if there's none - just return a promise. `opts` are simply redundant and unnecessary.

There's just way to much complexity for such simple code, it could be reduced to improve long term support and overall project's QA.

**Comment by yuriy-yarosh** [comment]
It's just pointless to aggro a guy who came out of nowhere with some suggestions, and treating 'em like personal criticism. In any case, that guy might be right, at some point, and you would miss an opportunity to gain something.

**Comment by rhetr** [comment]
in any case thanks for that short primer @pfrazee. I think some of my confusion was from using the [hyperdiscovery](https://github.com/karissa/hyperdiscovery) library as well.

**Comment by fsteff** [comment]
To add my two cents:
The api and especially the internals may be a little confusing, but that is no reason to break a stable api.
Adding a few small inline comments might improve the readability of the code immensely - like documenting function parameter and member types. 
Also, @type comments help the IDEs to give better autocompletion hints.

Anyway, great work!
