### ISSUE TITLE
Add unreplicate()

### ISSUE THREAD

**Issue by pfrazee** [mafintosh/hypercore#48]
We need a method to stop any active replication streams on hypercores.

**Comment by pfrazee** [comment]
I'll create a PR this evening.

**Comment by pfrazee** [comment]
I'll need some help from @mafintosh here. It looks to me like the only place the active streams are tracked are in the connection stream itself (?). But I'm very unclear about how the replication stream gets connected to the right sockets. :(

**Comment by mafintosh** [comment]
@pfrazee when replicating it creates an internal peer object to track replication state. it is added to the feed being replicated here, https://github.com/mafintosh/hypercore/blob/master/lib/replicate.js#L96

when unreplicating you basically just need to call the `onend` method that is being called on disconnect as well, https://github.com/mafintosh/hypercore/blob/master/lib/replicate.js#L231-L242

to find the correct peer, iterate the .peers list on the feed and look for the correct stream

``` js
for (var i = 0; i < feed.peers.length; i++) {
  if (feed.peers[i].stream === stream) {
    // assuming you expose the internal onend method on the peer as .disconnect or something
    feed.peers[i].disconnect()
  }
}
```

Hope this helps. Otherwise ping me again. Can do a hangout as well if you want.
